Add ItemModelRegistration
Buggy :
Need to have texture named block/andesite/name
But then conflict with recipes and loottable names
java.nio.file.NoSuchFileException: Chisel-for-fabric\bin\main\data\chiselforfabric\loot_tables\blocks\block\andesite\french-2.json